name: RezSez
favicon: null
layout_spectrum: 0.98532
typography_spectrum: 0.26408
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#170f0c'
    - '#feffd1'
    - '#6a88a2'
    - '#ffb371'
    - '#874c22'
  brandStrength: 0.625
  lightness: 0.7539979908615351
  saturation: 0.6502086066175252
  rhythmicContrast: 0.44901733403094113
purpose: []
